# Generated by Django 5.0.1 on 2024-02-17 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_authority_alter_order_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='authority',
            new_name='zarinpal_authority',
        ),
    ]
